product_manager/product_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from pages.views import contact_view

urlpatterns = [
    path('', include('products.urls')),
    path('contact/', contact_view, name='contact'),
    path('admin/', admin.site.urls),
]

product_manager/products/urls.py
from django.urls import path

from products.views import product_list_view
from products.views import product_detail_view
from products.views import product_create_view
from products.views import product_delete_view

app_name = 'products'

urlpatterns = [
    path('', product_list_view, name='product-list'),
    path('create/', product_create_view, name='product-create'),
    path('<int:id>/', product_detail_view, name='product-detail'),
    path('<int:id>/delete/', product_delete_view, name='product-delete'),
]

product_manager/pages/models.py
from django.db import models

# Create your models here.

product_manager/products/models.py
from django.db import models
from django.urls import reverse

class Product(models.Model):
    title = models.CharField(max_length=120)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True)
    newproduct = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse("products:product-detail", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("products:product-delete", kwargs={"id": self.id})

product_manager/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'title',
            'price',
            'description'
        ]

product_manager/pages/views.py
from django.shortcuts import render

def contact_view(request, *args, **kwargs):
    context = {
        'my_name': "Bruno Martins",
        'my_email': "bmartins.eng@gmail.com",
        'my_phone_ddd': 48,
        'my_phone_number': 996435380
    }
    return render(request, "contact.html", context)

product_manager/products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product
from .forms import ProductForm

def product_create_view(request, *args, **kwargs):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("../../")

    context = {
        "form": form
    }
    return render(request, "product_create.html", context)

def product_delete_view(request, id=1):
    pdt = get_object_or_404(Product, id=id)
    if request.method == "POST":
        pdt.delete()
        return redirect("../../")

    context = {
        "product": pdt
    }
    return render(request, "product_delete.html", context)

def product_list_view(request, *args, **kwargs):
    pdt = Product.objects.all()

    context = {
        "products": pdt
    }
    return render(request, "product_list.html", context)

def product_detail_view(request, id):
    pdt = get_object_or_404(Product, id=id)

    context = {
        "product": pdt
    }
    return render(request, "product_detail.html", context)

product_manager/products/templates/product_create.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="Save">
    </form>
{% endblock %}

product_manager/products/templates/product_delete.html
{% extends 'base.html' %}

{% block content %}
    <form action="." method="POST">
        {% csrf_token %}
        <h1>Are you sure you want to DELETE product {{product.title}}?</h1>
        <p><input type="submit" value="Yes"/><a href="../">Cancel</a></p>
    </form>
{% endblock %}

product_manager/products/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{product.title}}</h1>
    <p>Description: {% if product.description != '' %}{{product.description}}{% else %}Not avaiable{% endif %}</p>
    <p>Price: {{product.price}}</p>
    <a href={{product.get_delete_url}}>Delete</a>
{% endblock %}

product_manager/products/templates/product_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Current products</h1>
    {% for product in products %}
        <p>{{product.id}} - <a href="{{product.get_absolute_url}}">{{product.title}}</a></p>
    {% endfor %}
    <a href={% url 'products:product-create' %}>Create new product</a>
{% endblock %}

product_manager/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>First Django App</title>
    </head>
    <ul>
        <li><a href={% url 'products:product-list' %}>Products</a></li>
        <li><a href={% url 'contact' %}>Contact</a></li>
    </ul>
    <body>
        {% block content %}
            replace me
        {% endblock %}
    </body>
</html>

product_manager/templates/contact.html
{% extends 'base.html' %}

{% block content %}
    <h1>Contact me:</h1>
    <p>Name: {{my_name}}</p>
    <p>E-mail: {{my_email}}</p>
    <p>Phone: ({{my_phone_ddd}}) {{my_phone_number}}</p>
{% endblock %}